### ISSUE TITLE
Destinations are randomly filtered

### ISSUE THREAD

**Issue by fl0wfr** [yyrkoon94/lovelace-idf-mobilite#49]
Hi,

I just noticed that the destination stops are randomly filtered. When I first configured the layout, I had no issue when filtering destinations. Without any change on my side, I noticed that most of the time destinations are no longer filtered, but sometimes it's properly filtered, without understanding why it suddenly works.

Example:
```
type: custom:idf-mobilite-card
lineType: RER
entity: sensor.prim_le_raincy
show_screen: true
display_info_message: true
messages: sensor.prim_le_raincy_messages
exclude_lines_ref: 41039;471788;472324;471173;472240;
second_entity: sensor.prim_la_defense_e
exclude_second_lines_ref: >-
  41043;41022;41126;472393;471450;472958;472817;471445;471983;487016;487015;487014;487013;487012;487010;
nb_departure_first_line: "5"
nb_departure_second_line: "5"
```

![Image](https://github.com/user-attachments/assets/c8a03d09-01f4-4d80-89de-cca4dbf9a528)

Thanks for the project by the way :)

**Comment by fl0wfr** [comment]
You don't see the screenshot in the issue?
If so, you can see that it displays trains to Chelles - Gournay, but I filtered all Chelles - Gournay station rails in the config.

**Comment by yyrkoon94** [comment]
No, on the screenshot it's the train name (CONY, TINU, ...) can you edit the card and select "Afficher les références des lignes" and share the screenshot ?

**Comment by fl0wfr** [comment]
Oh, I see. Should I take the ID displayed in the layout instead of searching for the platform IDs from the referential?

**Comment by yyrkoon94** [comment]
Hmmm this is an old bug ... do you use the last version ?
Can you share your rest sensor configuration ?

**Comment by yyrkoon94** [comment]
Normally with the last version you must have something like that :

<img width="510" alt="Image" src="https://github.com/user-attachments/assets/857ed912-e740-44fe-8a11-b55cd0c5a457" />

**Comment by fl0wfr** [comment]
Sure!
```
sensor:
  - platform: rest
    name: prim_le_raincy
    unique_id: <redacted>
    resource: https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring
    method: GET
    params:
      MonitoringRef: "STIF:StopArea:SP:47901:"
      LineRef: "STIF:Line::C01729:"
    headers:
      apiKey: <redacted>
    scan_interval: 60
    timeout: 30
    value_template: "OK"
    json_attributes:
      - Siri
  - platform: rest
    name: prim_le_raincy_messages
    unique_id: <redacted>
    resource: https://prim.iledefrance-mobilites.fr/marketplace/general-message
    method: GET
    params:
      StopPointRef: "STIF:StopArea:SP:47901:"
      LineRef: "STIF:Line::C01729:"
    headers:
      apiKey: <redacted>
    scan_interval: 60
    timeout: 30
    value_template: "OK"
    json_attributes:
      - Siri
```
I just forced the update, restarted home-assistant, but same issue :(
