### ISSUE TITLE
Ratp cap lines invisible

### ISSUE THREAD

**Issue by tikifarm** [yyrkoon94/lovelace-idf-mobilite#5]
Hi,
any line from RATP cap is not showing at all and becomes fully invisible when leaving the HA configuration screen
![image](https://github.com/yyrkoon94/lovelace-idf-mobilite/assets/42776726/8eb807eb-2a4e-43f3-9f5f-d037400f3ee6)

i haven't tested (and don't know other groups) on other groupes, but for RATP cap lines, (tram t10 or line 15, 60 and more) it seems to not load at all, while  the request seems successful (attribute texts seems to show all needed information) 
it also seems to affect RATP line 290 

thanks :D

**Comment by yyrkoon94** [comment]
Hello,

Can you give me more details with the MonitoringRef and/or the LineRef you used i n your PRIM configuration ?

**Comment by tikifarm** [comment]
for the card on HA : 

```
type: custom:idf-mobilite-card
entities: ''
messages: ''
lineType: BUS
show_screen: false
exclude_lines: ''
entity: sensor.prim_JPT6v2   
```
on the config.yaml
```
sensor:
  - platform: rest
    name: prim_JPT6v2                           
    unique_id: uniqueID        
    resource: https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring
    method: GET
    params:
      MonitoringRef: "STIF:StopPoint:Q:486812:"
    headers:
      apiKey: "API key"                                 
    scan_interval: 60                                     
    timeout: 30
    value_template: "OK"
    json_attributes:
      - Siri
```

or if i chose any tram line connected with the T10, there is the same issue (47746)
